![data-x](http://oi64.tinypic.com/o858n4.jpg)






# Homework 02

## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 10-19 (inclusive), and b should be ten evenly spaced numbers between 1-7. Print all the results below:__ 


i) Square all the elements in both arrays (element-wise)  
ii)  Add both the squared arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)__


In [23]:
import numpy as np
a=np.arange(10,20)
print('a=',a)
b=np.linspace(1,7,10)
print('b=',b)
square_a=a**2
square_b=b**2
addsquare=square_a+square_b
print('square_a=\n',square_a)
print('square_b=\n',square_b)
print('addsquare=\n',addsquare)
sum_addsquare=0
for i in range(0,len(addsquare)):
    if i%2==0:
        sum_addsquare+=addsquare[i]
print('Sum of the elements with even indices of the added array=\n',sum_addsquare)
print('the square root of the added array=\n',np.sqrt(addsquare))

a= [10 11 12 13 14 15 16 17 18 19]
b= [ 1.          1.66666667  2.33333333  3.          3.66666667  4.33333333
  5.          5.66666667  6.33333333  7.        ]
square_a=
 [100 121 144 169 196 225 256 289 324 361]
square_b=
 [  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]
addsquare=
 [ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]
Sum of the elements with even indices of the added array=
 1105.0
the square root of the added array=
 [ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


__1b) Append b to a, reshape the appended array so that it is a 5x4, 2d array and store the results in a variable called m. Print m.__


In [3]:
m=np.hstack((a,b)).reshape(5,4)
print(m)

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


__1c) Extract the second and the third column of the m matrix. Store the resulting 5x2 matrix in a new variable called m2. Print m2.__


In [4]:
m2=m[:,1:3]
print(m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [5]:
m3=m2.T.dot(m)
print(m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


__1e) Round the m3 matrix to two decimal points. Store the result in place and print the new m3.__


In [6]:
new_m3=m3.round(decimals=2,out=None)
print(new_m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


__1f) Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, and the lowest value is at the bottom right. Print the sorted m3 array.__


In [30]:
sorted_m3=np.sort(-m3,axis=-1,kind='quicksort',order=None)
newsorted_m3=-np.sort(sorted_m3,axis=0,kind='quicksort',order=None)
print(newsorted_m3)

[[ 748.11111111  697.33333333  482.33333333  437.88888889]
 [ 489.88888889  454.55555556  437.88888889  402.22222222]]


## NumPy and Masks
__2a) create an array called 'f' where the values are sin(x) for x from 0 to pi with 100 values in f__
* print f
* use a 'mask' and print an array that is True when f >= 1/2 and False when f < 1/2
* create and print an array sequence that has only those values where f>= 1/2



In [14]:
from numpy import pi
x = np.linspace(0,pi, 100)
f=np.sin(x)
print(f)
mask=f>=1/2
print(mask)
f[mask]

[  0.00000000e+00   3.17279335e-02   6.34239197e-02   9.50560433e-02
   1.26592454e-01   1.58001396e-01   1.89251244e-01   2.20310533e-01
   2.51147987e-01   2.81732557e-01   3.12033446e-01   3.42020143e-01
   3.71662456e-01   4.00930535e-01   4.29794912e-01   4.58226522e-01
   4.86196736e-01   5.13677392e-01   5.40640817e-01   5.67059864e-01
   5.92907929e-01   6.18158986e-01   6.42787610e-01   6.66769001e-01
   6.90079011e-01   7.12694171e-01   7.34591709e-01   7.55749574e-01
   7.76146464e-01   7.95761841e-01   8.14575952e-01   8.32569855e-01
   8.49725430e-01   8.66025404e-01   8.81453363e-01   8.95993774e-01
   9.09631995e-01   9.22354294e-01   9.34147860e-01   9.45000819e-01
   9.54902241e-01   9.63842159e-01   9.71811568e-01   9.78802446e-01
   9.84807753e-01   9.89821442e-01   9.93838464e-01   9.96854776e-01
   9.98867339e-01   9.99874128e-01   9.99874128e-01   9.98867339e-01
   9.96854776e-01   9.93838464e-01   9.89821442e-01   9.84807753e-01
   9.78802446e-01   9.71811568e-01

array([ 0.51367739,  0.54064082,  0.56705986,  0.59290793,  0.61815899,
        0.64278761,  0.666769  ,  0.69007901,  0.71269417,  0.73459171,
        0.75574957,  0.77614646,  0.79576184,  0.81457595,  0.83256985,
        0.84972543,  0.8660254 ,  0.88145336,  0.89599377,  0.909632  ,
        0.92235429,  0.93414786,  0.94500082,  0.95490224,  0.96384216,
        0.97181157,  0.97880245,  0.98480775,  0.98982144,  0.99383846,
        0.99685478,  0.99886734,  0.99987413,  0.99987413,  0.99886734,
        0.99685478,  0.99383846,  0.98982144,  0.98480775,  0.97880245,
        0.97181157,  0.96384216,  0.95490224,  0.94500082,  0.93414786,
        0.92235429,  0.909632  ,  0.89599377,  0.88145336,  0.8660254 ,
        0.84972543,  0.83256985,  0.81457595,  0.79576184,  0.77614646,
        0.75574957,  0.73459171,  0.71269417,  0.69007901,  0.666769  ,
        0.64278761,  0.61815899,  0.59290793,  0.56705986,  0.54064082,
        0.51367739])

## NumPy and 2 Variable Prediction

__ Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [16]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ',x)
print ('y= ',y)

x =  [  1.34683976   1.12176759   1.51512398   1.55233174   1.40619168
   1.65075498   1.79399331   1.80243817   1.89844195   2.00100023
   2.3344038    2.22424872   2.24914511   2.36268477   2.49808849
   2.8212704    2.68452475   2.68229427   3.09511169   2.95703884
   3.09047742   3.2544361    3.41541904   3.40886375   3.50672677
   3.74960644   3.64861355   3.7721462    3.56368566   4.01092701
   4.15630694   4.06088549   4.02517179   4.25169402   4.15897504
   4.26835333   4.32520644   4.48563164   4.78490721   4.84614839
   4.96698768   5.18754259   5.29582013   5.32097781   5.0674106
   5.47601124   5.46852704   5.64537452   5.49642807   5.89755027
   5.68548923   5.76276141   5.94613234   6.18135713   5.96522091
   6.0275473    6.54290191   6.4991329    6.74003765   6.81809807
   6.50611821   6.91538752   7.01250925   6.89905417   7.31314433
   7.20472297   7.1043621    7.48199528   7.58957227   7.61744354
   7.6991707    7.85436822   8.03510784   7.80787781   8.22410224
   7.9

__3a) Find Expected value of x and the expected value of y__

In [20]:
E_x=x.mean()
E_y=y.mean()
print(E_x)
print(E_y)

5.78253254159
11.0129816833


__3b) Find variance of distributions of  x and  y__

In [39]:
var_x=((x-E_x)**2).mean()
print(var_x)

7.03332752948


In [40]:
var_y=((y-E_y)**2).mean()
print(var_y)

30.1139035755


__3c) Find co-variance of x and y.__

In [41]:
cov_xy=((y-E_y)*(x-E_x)).mean()
print(cov_xy)

14.5111663945


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
ie y_predicted = f(x) = y0+mx.__  

In [42]:
m=cov_xy/var_x
print(m)

2.06320071597


In [43]:
y0=E_y-m*E_x
print(y0)

-0.917543596587


__3e) Predict y for each value in x, pur the error into an array called y_error__

In [47]:
predict_y=y0+m*x
print(predict_y)

[  1.86125717   1.39688809   2.20846128   2.28522836   1.98371207
   2.48829527   2.78382468   2.80124813   2.9993232    3.21092152   3.8988
   3.67152796   3.7228942    3.9571493    4.23651436   4.9033035
   4.62116978   4.61656787   5.46829307   5.18342105   5.45873164
   5.79701128   6.12915141   6.11562653   6.31753758   6.81864709
   6.61027849   6.86515115   6.43505522   7.35780389   7.65775187
   7.46087825   7.38719373   7.85455455   7.66325667   7.88892606
   8.00622544   8.33721481   8.95468038   9.08103323   9.33034895
   9.78539799  10.00879629  10.06070164   9.53754157  10.38056671
  10.36512531  10.72999716  10.42269073  11.25028634  10.81276185
  10.97218988  11.35052091  11.83583685  11.38990445  11.51849632
  12.58177632  12.49147206  12.98850691  13.14956122  12.50588416
  13.35028889  13.5506705   13.31658991  14.17094102  13.947246
  13.74018137  14.51931443  14.74126735  14.79877137  14.96739089
  15.28759454  15.66049665  15.1916755   16.05043004  15.57498655
  16

In [48]:
error_y=y-predict_y
print(error_y)

[-0.19775597  0.62457111 -0.10030076 -0.02506341 -0.02083649  0.46716823
  0.24499418  0.53440482 -0.24466541  0.21408918 -0.50209852 -0.27775029
  0.06213923  0.42578118  0.0931215  -0.86405311  0.1157489  -0.31558388
 -0.62666017 -0.40166149 -0.46107377 -0.47954311 -0.3607047  -0.17838904
 -0.58942116 -0.10891094  0.07115518 -0.29032384  0.74232081  0.19082863
 -0.35553767 -0.14062095  0.39304511  0.0567791   0.61328502  0.80310676
  0.77597321  0.12176065 -0.06373323 -0.26383402 -0.45927925 -0.12347238
 -0.60673379 -0.20079382  0.0660562  -0.30670405  0.33067419 -0.062778
  0.75987212 -0.67596798  0.65468531 -0.02820071 -0.08606832  0.26171143
  0.72997592  0.60306068 -0.40563939 -0.05397013  0.02061681 -0.28548928
  0.7405245  -0.58908804 -0.43343988  0.76182107  0.02727604  0.32564401
  0.56606805  0.11129392 -0.46417555  0.27572093 -0.5147747  -0.16862142
 -0.42262995  0.08035574 -0.72551112  0.43596616 -0.71282602  0.11027337
  0.16964259 -0.14132301 -0.58920807  0.31716141 -0.1

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__

In [51]:
average_error=(error_y**2).mean()
print(average_error)

0.174454680849


In [53]:
RMSE=np.sqrt(average_error)
print(RMSE)

0.417677723669
